### ISSUE TITLE
SqlDistributed lock never gets released on dispose

### ISSUE THREAD

**Issue by mturczyn** [madelson/DistributedLock#100]
With such code:
```
class Program
{
    private static SqlConnection _sqlConn = new SqlConnection("my connection string");
   
    static void Main(string[] args)
    {
        int pid;
        using (var p = Process.GetCurrentProcess()) { pid = p.Id; }
        TestSqlLocking(pid).Wait();
    }

    private static async Task TestSqlLocking(int processId)
    {
        _sqlConn.Open();
        var t1 = DoWorkAsyncWithSqlLock($"Process {processId} Client 1");
        var t2 = DoWorkAsyncWithSqlLock($"Process {processId} Client 2");
        var t3 = DoWorkAsyncWithSqlLock($"Process {processId} Client 3");
        var t4 = DoWorkAsyncWithSqlLock($"Process {processId} Client 4");
        await Task.WhenAll(t1, t2, t3, t4);
    }

    private static async Task DoWorkAsyncWithSqlLock(string client)
    {
        var sqlDistributedLock = new SqlDistributedLock("myLock", _sqlConn);
        Console.WriteLine($"Before taking the lock for client [{client}]");
        await using (await sqlDistributedLock.AcquireAsync(TimeSpan.FromSeconds(10)))
        {
            Console.WriteLine($"After taking the lock for client [{client}]");
            Console.WriteLine($"Doing some work and releasing lock for client [{client}]");
        }
    }
}
```
I always get the timeout after lock is first acquired. Then it never gets released.

**Comment by madelson** [comment]
@mturczyn thanks for reaching out. Just looking at your initial repro code, an issue I see is that you are trying to use the same `SqlConnection` object concurrently across multiple threads (tasks). However, `SqlConnection` is not thread-safe and cannot be used in this way. 

Either you should create a separate `SqlConnection` instance for each task, or you need to await each task as you create it rather than creating the 4 tasks to run in parallel and then doing WhenAll.

Does that make sense?

**Comment by mturczyn** [comment]
@madelson Thank you for quick response. Oh, ok, thank you for response :) But in real solution I need this to completely parallel, as it will come from multiple application instances. Anyway, I saw the source code and I noticed that when connection string is passed, connection (or transaction) is manager inside the lock and that is exactly what I need :)
