### ISSUE TITLE
UseMultiplexing causes errors on old mysql/mariadb versions

### ISSUE THREAD

**Issue by tvoyle** [madelson/DistributedLock#123]
On mysql versions before 5.7, mariadb versions before 10.0.2 only one lock can be held per connection. Connection reuse causes any lock held to be released as soon as another lock is acquired.

**Comment by madelson** [comment]
Hi @tvoyle thanks for reporting. Given that there are old versions and multiplexing can be disabled via options, this seems like something that should go into the documentation rather than something to change in the library.

If you provide me with the error numbers and SQL States associated with this error we can add a new error handling case [here](https://github.com/madelson/DistributedLock/blob/master/DistributedLock.MySql/MySqlUserLock.cs#L66) that would throw a more descriptive error message telling you to disable multiplexing when using the older database version.

Does that path make sense?

**Comment by madelson** [comment]
Seems like this is not an error; it just releases previous locks. See "important" note here: https://dev.mysql.com/doc/refman/5.6/en/locking-functions.html
