### ISSUE TITLE
Is the reader writer lock preferring writers or readers?

### ISSUE THREAD

**Issue by CatalinAdlerDF** [madelson/DistributedLock#125]
Hi,

Awesome library you have here.
Was just wondering how does the reader writer lock behave when there are queued readers and writers?
Does it honor the writer first? fifo? 

Thanks!

**Comment by madelson** [comment]
The general policy is that writers get precedence over readers (since otherwise a stream of overlapping readers would block out writers forever).

In cases where the RW lock implementation is fully contained inside the back-end (e. g. SQL Server), in theory they could have some more nuanced policy going on there. I'm not aware of anything like this, but it could be worth reading the docs on the specific back-end you'll be using if that behavior is very important to you.

However, at a minimum *all* RW lock back-ends we have today pass this test: https://github.com/madelson/DistributedLock/blob/master/DistributedLock.Tests/AbstractTestCases/DistributedReaderWriterLockCoreTestCases.cs#L50

**Comment by CatalinAdlerDF** [comment]
nice.

the behavior i seek is writer priority which is: when a writer gets queued, existing readers finish and new readers get behind the writer.

the backends i am open to are redis, mysql and maybe zookeepr

**Comment by madelson** [comment]
Yep that should be the standard behavior!
