### ISSUE TITLE
Cannot create a RedisDistributedSemaphore with extensionCadence set to Timeout.InfiniteTimeSpan

### ISSUE THREAD

**Issue by LinkForce** [madelson/DistributedLock#130]
I am trying to instantiate a RedisDistributedSemaphore that doesn't auto extends the locks, and according to the source code, I should set extensionCadence set Timeout.InfiniteTimeSpan. But when the RedisDistributedSyncronizationOptions is built, I get an ArgumentOutOfRangeException stating that "extensionCadence must be less than expiry". I believe this is not right, as Timeout.InfiniteTimeSpan is less than the default expiry.
![image001](https://user-images.githubusercontent.com/13049395/171472969-8a6ec44b-fec5-49ec-8aa5-1b2ebf6c5137.png)

**Comment by madelson** [comment]
@LinkForce thanks for reporting. This does seem like a bug. Out of curiosity why do you want to disable auto-extension?

**Comment by madelson** [comment]
I see thanks for the context. The way the library works it will auto-release the semaphore if the handle gets garbage collected. So the way I’d recommend doing this is:

`var handle = await semaphore.AcquireAsync();
Task.Delay(timeout).ContinueWith(() => handle.Dispose());`

**Comment by madelson** [comment]
@Skier23 ok. Just want to confirm that you're aware that if you let the handle be GC'd it will be released before the expiry. E.g. you can't do something like this:

```
await this._semaphore.AcquireAsync(); // discard result
// assume semaphore is held here... but it isn't!
```

**Comment by Skier23** [comment]
yes. I have teams that are doing something like
var lock = ...acquireasync(10)
//assume lock will last 10 seconds and know that their logic will take less than 10seconds
//do logic

I know this isn't good practice and I'm trying to get them away from doing it like this but that's how some teams are doing it now.

**Comment by madelson** [comment]
@Skier23 is the code you show using the `DistributedLock` library already or some other implementation? If you're using the `DistributedLock` library like this it isn't just bad practice, you might have a bug because if the handle becomes eligible for GC (which could happen any time once there are no more references to it

**Comment by Skier23** [comment]
Its currently using another implementation.

**Comment by madelson** [comment]
I finally had some time to look into this in more depth.

I'm coming around to the opinion that **the thing I want to change here is the misleading error message** that implies that one *should* be allowed to set ExtensionCadence to infinite. This error message appears to have been copied from `AzureBlobLeaseOptionsBuilder`, which does have a use-case for disabling extension because the underlying provider supports infinite lease durations. There are a couple indicators that the current behavior is what's intended:
* We have a test for it in RedisDistributedSynchronizationOptionsBuilderTest
* The doc comments on the ExtensionCadence setter do not document infinite as an option.

In order to support disabling extension, we'd need to actually do quite a bit more than just change the one check. We'd have to:
* Update RedLockHandle's implementation of ILeaseMonitor to handle this case in both MonitoringCadence and RenewOrValidateLeaseAsync.
* To support handle-loss-checking, we'd need to implement an alternative check-but-don't renew script for each of the primitives (mutex, rwlock, and semaphore).
* Add test coverage for this alternate flow

This wouldn't be that big a deal if the use-case was really strong, but I still don't feel like I see it.

For @LinkForce's use-case, the error actually stopped them from accidentally writing broken code. If this change were implemented, the code would have failed to do the right thing in a silent and subtle way rather than failing fast.

For @Skier23's use-case it feels like we're just trying to support a known-to-be-bad pattern, when the default behavior of this library makes it trivial to support a very robust pattern instead.

Furthermore, even as-written the library does indirectly support the pattern of using the semaphore as a time-based rate-limiter rather than a true semaphore. This can be done simply with:
```
var handle = await sempahore.AquireAsync();
Task.Delay(timeout).ContinueWith(() => handle.Dispose());
```
This can easily be wrapped up in a utility method.

If this use-case of "distributed rate-limiter" is a popular one, I wonder if it merits consideration for a dedicated API in the library.? For example, we could have something like this:

```
class RedisDistributedRateLimiter
{
    public RedisDistributedRateLimiter(string name, int maxCount, TimeSpan period);

    // WaitAsync returns only maxCount times/period
    public async Task WaitAsync(CancellationToken);
}
```
