### ISSUE TITLE
Question: How might I wrap the library to provide the same semantics?

### ISSUE THREAD

**Issue by stephenpatten** [madelson/DistributedLock#22]
Hello,

Wanted to decorate the SqlDistributedLock in such a fashion that the I can run other code to validate (beyond the acquired lock) that I truly have a lock on a business object. 

If I can acquired both a lock from SqlDistributedLock and the business object, then I can really lock and return your handle. I like the usage of the using statement with Acquire and TryAcquire and have started with this interface
  
    public interface IAWDLock : IDisposable
    {
        IDisposable Acquire();
        IDisposable Acquire(TimeSpan timeout);
    }

but, I'm unsure (haven't read enough of your code) if this looks ok, and more importantly that the implementation is sound. The IDisposable handed out from the Acquire method, is that what would trigger the Disposed call on the class? I'm a bit confused as you can tell. Here's what I have so far.

    public class AWDSqlLock : IAWDLock
    {
        public IDisposable Acquire()
        {
        }

        public IDisposable Acquire(TimeSpan timeout)
        {
        }

        public void Dispose()
        {
        }
    }

So at this point I'm reading the [docs](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/statements#the-using-statement) as a refresher of how the using statement translates into the try/finally.

Thank you,
Stephen

**Comment by madelson** [comment]
Hi @stephenpatten . I'm not sure I fully understand what you are trying to do and in particular what this means:

> Wanted to decorate the SqlDistributedLock in such a fashion that the I can run other code to validate (beyond the acquired lock) that I truly have a lock on a business object.

One thing I'll note is that I'm not sure why you have your AWDSqlLock class implementing IDisposable. Maybe there is a reason for this separate from the code you've shown.

As you say, `using` is just syntax sugar over try-finally. The translation is this:

```
using (var handle = myLock.TryAcquire(...))
{
    ...
}

// translates to
var handle = myLock.TryAcquire(...);
try
{
   ...
}
finally 
{
    if (handle != null) { handle.Dispose(); }
}
```

In your case, it seems like you want to return the handle to the caller, so you wouldn't want a using block there because that would dispose the handle. Instead, the caller would have the using block:

```
AWDSqlLock awdLock = ...
using (var handle = awdLock.TryGetLock(...))
{
    if (handle != null) { /* got the lock: do something */ }
}
```

The one thing you should be careful of is that if `AWDSqlLock` is going to do any logic between acquiring the underlying `SqlDistributedLock` handle and returning it that could fail, then you want a try-catch to make sure the handle gets cleaned up promptly (otherwise you'd need to wait for GC). For example:

```
// check the distributed lock
if (sqlHandle != null)
{
      try
      {
          if (AdditionalBusinessLogic()) { return sqlHandle; }
      }       
      catch
      {
          sqlHandle.Dispose(); // clean up
          throw; // propagate the biz logic error
      }

      // result is neg
      sqlHandle.Dispose(); // clean up
      return null;
}
```
