### ISSUE TITLE
Postgres lock held for <= 1min if process crashes

### ISSUE THREAD

**Issue by deepforest** [madelson/DistributedLock#230]
Thanks for this great library!!

Could you please move the hardcoded 1-min monitoring sleep time to the Options of any provider?

```
// 1-min increments is kind of an arbitrary choice. We want to avoid this being too short since each time
        // we "come up to breathe" that's a waste of resources. We also want to avoid this being too long since
        // in case people have some kind of monitoring set up for hanging queries
        await connection.SleepAsync(
                sleepTime: TimeSpan.FromMinutes(1),
                cancellationToken: cancellationToken,
                executor: (command, token) => command.ExecuteNonQueryAsync(token, disallowAsyncCancellation: false, isConnectionMonitoringQuery: true)
            ).TryAwait();
```

Implementing a Leader Election mechanism, where only one process should be the leader, when the leader process crashes, all others need to wait up to 1-min to be elected. This is unacceptable in such scenario where the retried leader must be replaced ASAP.

Also, why everything in DistributedLock.Core is set to internal?
I couldn't create my own DistributedLock.Postgres provider to override/ignore this value without copying all the code.

**Comment by madelson** [comment]
> Implementing a Leader Election mechanism, where only one process should be the leader, when the leader process crashes, all others need to wait up to 1-min to be elected. This is unacceptable in such scenario where the retried leader must be replaced ASAP.

@deepforest can you explain your use case a bit more? What role do the locks take in leader election?

the 1-min timeout you are referring to is only for tracking loss of the lock handle through handle.CancellationToken, which is generally an error condition.

That said, I could see allowing this parameter to be customized via the options if there is a use-case for it.

> Also, why everything in DistributedLock.Core is set to internal?
I couldn't create my own DistributedLock.Postgres provider to override/ignore this value without copying all the code.

It’s internal because those are implementation details and I’m not committing to any sort of cross-version compatibility for those internal APIs.

**Comment by deepforest** [comment]
@madelson, thanks for referring this issue quickly.

I'm using distributed lock in my leader election implementation as follows:

* There's a `while` loop which calls the code below each 1 second. It tries to acquire the lock. If the lock acquired or already acquired from before, it's considered the leader instance, so for example, it's responsible to keep TCP connection to another party (only one allowed - limitation) and for reading pending tasks in DB table and execute them by sending them to the third party.
* If you gracefully terminate a Leader instance, it will release the distributed lock and another one will hold it and will become the new leader.
* But if a Leader instance crashes, it won't releases the lock, and the Library's Monitoring mechanism, will release it after 1-minute, which is too late for the leadership requirement. I wish this 1-minute be configurable.

```
try
{
    if (_lockHandle is { HandleLostToken.IsCancellationRequested: false })
    {
        _logger.LogDebug("Already leader");
        return;
    }
    
    _logger.LogDebug("Trying to acquire leadership lock");
    _lockHandle = await _lockProvider.AcquireLockAsync(
        LockId,
        TimeSpan.FromSeconds(_options.LockTimeoutSeconds),
        cancellationToken);
    
    // register for handle loss
    if (_lockHandle.HandleLostToken.CanBeCanceled) {
        _lockHandle.HandleLostToken.Register(() => {
            // lock connection lost, lease expired etc.
            // that means we are no longer leader
            NotifyLeaderChanged(false);

            // get rid of handle
            try {
                _lockHandle?.Dispose();
                _lockHandle = null;
            } catch { }
        });
    }
        
    NotifyLeaderChanged(true);
    _logger.LogDebug("Leadership confirmed/acquired");
}
catch (TimeoutException)
{
    if (_isLeader)
    {
        _logger.LogWarning("Lost leadership since could not acquire lock");
    }
    
    await ReleaseLeadershipAsync();
    NotifyLeaderChanged(false);
}
catch (Exception ex) when (ex is not OperationCanceledException)
{
    _logger.LogError(ex, "Error while trying to acquire leadership lock");
    await ReleaseLeadershipAsync();
    NotifyLeaderChanged(false);
}
```

**Comment by deepforest** [comment]
@madelson, any additional information required to your final decision, or should I clone the repo as-is and change whatever required on my end?

**Comment by madelson** [comment]
@deepforest thanks for the write up. I admit that I’m still a bit confused. If the leader instance crashes (meaning the process holding the lock crashes) then the handle lost token will never fire because it exists only in the leader process which has crashed.

However, if the leader process does not crash but instead loses its connection to the DB, then the handle lost token would let the leader know about this. I think you’re saying that in this case you want the leader to somehow notify the other processes that a new election is needed via some other channel, and that where the delay comes in. Is that right?

If so, I’d be open to a contribution which adds this configuration option. 

I think we need to be careful of the interaction with connection multiplexing; the simplest approach would be to forbid using this option without disabling multiplexing. Another more complex approach would involve making the multiplexer leverage the lowest among all active timeouts, but that might be more than you want to bite off (and could always be added later on).

**Comment by deepforest** [comment]
> @deepforest thanks for the write up. I admit that I’m still a bit confused. If the leader instance crashes (meaning the process holding the lock crashes) then the handle lost token will never fire because it exists only in the leader process which has crashed.

Indeed, and this is the problem. If it exits gracefully, lock released, mission done. If it not, I expect the lock to be released by progress.

> However, if the leader process does not crash but instead loses its connection to the DB, then the handle lost token would let the leader know about this. I think you’re saying that in this case you want the leader to somehow notify the other processes that a new election is needed via some other channel, and that where the delay comes in. Is that right?

Not exactly, I thought more about a mechanism in Postgres side, something like: "Please hold this lock for 2 seconds, if the locker is not pinging you back withing 2 seconds, release the lock.

Maybe I missed it, but I thought this is what the "monitoring mechanism with 1-min does".

**Comment by madelson** [comment]
The underlying mechanism here is Postgres advisory locks which are scoped to a database connection. Once acquired, the lock will be held so long as the connection stays alive (until released).

Scenario 1: Sometimes, a network issue or other transient problem can kill a connection prematurely. In that case an application that thinks it is holding the lock might not really have it any more. The HandleLostToken is meant to detect this; it does so by issuing queries on the connection while the lock is held to detect whether it is still alive. Effectively it tells the owner of a lock handle that the handle has become invalid prematurely.

Note that you could also achieve this by passing your own connection to the lock and then polling on that connection as frequently as you’d like once the lock is acquired.

Scenario 2: if the application crashes, then the problem of detecting whether the connection is still alive happens on the Postgres side. I don’t know much about how this works (how long it waits before tearing down a connection due to an unresponsive client). Potentially there is connection-string-level or database-level configuration that impacts this.

Sounds like you’re interested in Scenario 2?

**Comment by deepforest** [comment]
I got it all wrong, thinking that somehow the monitoring technique tells Postgres for how long the lock is to be held unless renewed. So yes, I'm interesting in Scenario 2. Maybe there's no such an option in Postgres at all and I'll have to find another way, not using Postgres advisory locks at all. Maybe a straight forward table will do the job, but might be less efficient.
In a better world, I would use Redis for that, but I have limitation of using Postgres only :)

**Comment by madelson** [comment]
Seems like Postgres has tcp_keepalive_* server variables which influence it. Potentially you can tighten those up to get it to react to a dead client process more quickly.

**Comment by deepforest** [comment]
Thanks for the reference, but I wouldn't do anything that will affect all globally just for this specific use case, also any explicit custom solution that I won't able to control using a managed service.

**Comment by madelson** [comment]
That makes sense. I haven't experimented, but potentially you could set those variables in session scope only on the connection you're using to acquire the lock.
