### ISSUE TITLE
Postgres Semaphore Implementation

### ISSUE THREAD

**Issue by AdemCatamak** [madelson/DistributedLock#231]
I noticed that the IDistributedSemaphoreProvider interface is implemented for SQL Server (SqlDistributedSynchronizationProvider).

Is this feature also provided for PostgreSQL?

If not, is there a specific reason why the IDistributedSemaphoreProvider interface is not implemented for PostgreSQL (PostgresDistributedSynchronizationProvider)?

Thank you for your effort and support!

**Comment by madelson** [comment]
@AdemCatamak thanks for your interest in the library.

Each provider (e.g. Postgres) has different innate capabilities so not every provider can or does implement every synchronization primitive.

In order to get a semaphore for Postgres, we'd need to come up with a viable way to implement it that meets the quality criteria (e.g. so far I've tried to avoid implementations that require the user to create a specific table on their database in advance).

If someone were to propose a compelling implementation path, I'd accept it as a contribution to the library.

Hope that helps,
Mike
