### ISSUE TITLE
Release 2.1 cleanup tasks

### ISSUE THREAD

**Issue by madelson** [madelson/DistributedLock#82]
- [x] Merge in master
- [x] Finalize version for Core (at least patch bump)
- [x] Release notes
- [x] Github release

**Comment by dstj** [comment]
@madelson Can I add a minor request to this list? Would be possible to also do a "github release" (instead of only a NuGet version upgrade) so that people (_i.e._ me) are automatically notified when watching your repo through GitHub's watch?

**Comment by madelson** [comment]
@dstj out of curiosity is there a particular issue or feature you're waiting for?

**Comment by dstj** [comment]
@madelson, nothing in particular, no. Well, I'm not sure yet actually ;) I'm looking to replace [RedLock.net](https://github.com/samcook/RedLock.net) w/ a Redis backend and I figured I would wait to try out the latest major version as I saw it was coming up. I figured there would be a 2.1 release for [DistributedLock.Redis](https://www.nuget.org/packages/DistributedLock.Redis/) as well as right now it's a 1.0.1.

**Comment by madelson** [comment]
@dstj yeah the milestone version is for the umbrella package (DistributedLock); the sub-packages have their own versions based on what changes are actually made.

Regarding Redis, I don't think I have any new Redis features planned for 2.1; is there something holding you back from using it?

**Comment by dstj** [comment]
@madelson 
> the sub-packages have their own versions based on what changes are actually made

Ah, I see. I think maybe to avoid confusion, the sub-packages (or at least DistributedLock.Core) should follow the same version number as the umbrella package as they are essentially _the same thing_.

Here's what happened. I came across this repo. I saw there was an all-in-one package and targeted packages. Since I always prefer using targeted packages, I looked at [DistributedLock.Core](https://www.nuget.org/packages/DistributedLock.Core/) and [DistributedLock.Redis](https://www.nuget.org/packages/DistributedLock.Redis/). Since they were on 1.0.1, I figured they were behind the 2.0.2 of the all-in-one package.

Since I now understand that DistributedLock.Core/Redis v1.0.1 == DistributedLock 2.0.2, I'll give it a go.

**Comment by madelson** [comment]
I should probably explain the versioning somewhere. The reason I've taken the approach is so that people who just install the sub-packages don't get hit with lots of unnecessary empty updates. However, I can see how that would be confusing!
