### ISSUE TITLE
Suitable for distributed azure applications

### ISSUE THREAD

**Issue by filoe** [madelson/DistributedLock#9]
Is this suitable for distributed azure applications?
What's about the performance of this library? Let's say compared to azure storage leases.

**Comment by madelson** [comment]
HI @filoe, thanks for your interest in the library.

> Is this suitable for distributed azure applications?

The `SqlDistributedLock` class and related SQL-based classes are designed for use in distributed applications. These classes leverage a central SQLServer's native sp_getapplock mechanism to coordinate locking between application threads and processes hosted on different servers.

While I haven't personally used the library on Azure, I know that at least one other has done so successfully (see [this issue](https://github.com/madelson/DistributedLock/issues/5)). One peculiarity of SqlAzure is it's aggressive timing out of idle connections. To better support this, version 1.3 of the library added a [special connection management strategy for Azure](https://github.com/madelson/DistributedLock#connection-management) to keep connection alive while the lock is held.

> What's about the performance of this library? Let's say compared to azure storage leases.

In my experience the performance is quite good. The actions to acquire and release a lock require one SQL query each which is typically very fast (unless acquiring a lock that someone else is holding). The library offers async acquire functions so that threads are not blocked while waiting for a lock.

That said, I haven't worked with Azure leases so I can't offer a direct comparison. If performance is a concern, I would recommend testing each approach under realistic workloads and levels of concurrency to see which one makes sense for your use-case.

**Comment by filoe** [comment]
Thanks for fast and detailed answer. 
I've got no experience in the field of large business applications. 
Do you know whether it still works if I use georeplication on azure for the database?
Is it still guaranteed that all instances (accross the world - accessing different instances of the database) are synchronized by the locking?

**Comment by madelson** [comment]
@filoe I don't have experience with Azure so I definitely can't say for sure. However, I think it's unlikely that locks would replicate. The nature of locking means that there must be realtime coordination between all parties involved; this doesn't work in an "eventually consistent" system. You'll have to try it and see!
