### ISSUE TITLE
File based lock - orphaned locks

### ISSUE THREAD

**Issue by dazinator** [madelson/DistributedLock#96]
I've been using the distributed file lock provider with an Azure File Share.

I have noticed that for some reason, there appears to be an orphaned lock file.

Can I ask, what happens if the process is abruptly terminated whilst a file lock is held? I take it there is no recovery process in place to clean up an orphaned lock file when the process next starts, or to identify / transfer ownership of the orphaned lock file somehow when attempting to acquire the same lock from the new process? Could this have been what lead to the orphaned lock file?

**Comment by madelson** [comment]
Here's how it should work:

* When the lock is acquired, we create the blob if it does not already exist. If we created the blob, we add a metadata key-value pair:  `(__DistributedLock, current date)`.
* When the lock is released, if it has the `__DistributedLock` metadata key, we delete it rather than just releasing the lease on it.

If the application terminates abruptly while a lock is held, this will result in an orphaned blob. I'm not sure if there's anything we can do about that unless Azure provides some way to naturally have blobs expire after some TTL. However, if an application later acquires a lock with *the exact same name*, it should delete that blob when the lock is released.

Note also that if you lock on a blob created by some other application (lacking the metadata key), DistributedLock will never attempt to delete that blob because for all we know it has actual content you care about.

Some questions:
* Does the orphaned blob you see have the metadata key?
* Have you tried acquiring/releasing the exact same lock name as the one that created that blob?

**Comment by dazinator** [comment]
For clarification - when you say 'blob' you are referring to the file right? I know you have another provider for azure blob storage and want to make sure we aren't crossing wires with that :-)

**Comment by madelson** [comment]
@dazinator oh sorry I misread you're comment. You're just using `FileDistributedLock`, right?

That one also attempts to clean up after itself by using `FileOptions.DeleteOnClose` to create the handles (see https://github.com/madelson/DistributedLock/blob/master/DistributedLock.FileSystem/FileDistributedLock.cs#L84). 

I think that this is supported natively on Windows so it might clean up even if the process aborts but for a distributed file system or on other OS's it wouldn't surprise me if an aborted process would not clean this up.

I assume based on your question that this is happening rarely (e. g. it's not that every single lock acquisition leads to an orphaned file)?

**Comment by madelson** [comment]
@dazinator I'm closing this for now since it has been inactive for a while. If you still have questions don't hesitate to post.
