### ISSUE TITLE
Comparison of locks

### ISSUE THREAD

**Issue by hoerup** [madelson/DistributedLock#97]
Is there any page comparing the performance of the various locking backends ?

**Comment by madelson** [comment]
Hi @hoerup . 

There isn't such a page today. I think it is hard to talk about "performance" of locking back-ends since that could depend a lot on factors like what hardware the back-end is running on, how it is configured (e. g. cluster size, network), and how much load it is under. For that reason, even though I could run some tests on my local machine, I don't think those tests would really tell you anything useful.

That said, there are two main differentiators to consider when comparing different implementations and thinking about how they will perform at scale. *These factors are documented under the 'implementation notes' section for each individual locking backend*:

### Cost to wait for a lock

Acquiring a lock when it is available is usually very cheap, about as cheap as any other query against that database/system. However, when there is contention and we are using Acquire() rather than TryAcquire(), we have to wait for the lock. 

With some technologies such as SqlServer, Postgres, and ZooKeeper allow for a very responsive wait: the remote system will notify the locking application when the wait has completed so we immediately detect that the lock has been acquired.

With other technologies such as Redis and Azure, we have to do a busy wait where we repeatedly sleep and re-try the acquire operation. This means that long waits/high contention result in more requests to the underlying system and also that there will be a (configurable) delay between when the lock becomes free and when the locking application becomes aware that it has acquired the lock.

### Cost to hold a lock

For relational database technologies (e. g. SqlServer and Postgres), holding a lock requires a connection. Most databases have a limit as to how many concurrent connections they allow, and also .NET apps typically set a maximum pool size to avoid allocating too many connections. Therefore, holding more locks for longer means more connections which consume system resources. The multiplexing feature in distributed lock can often greatly reduce this cost but does not eliminate it.

Other locking technologies like Redis and Azure uses leases (locks based on a timestamp in the backend). Therefore, they don't need to be actively connected to hold the lock. However, they will occasionally have to send queries to the backend to renew the lease.

Notably, ZooKeeper uses connection-based locking but does can multiplex any number of lock waits/holds on a single connection between the application and the backend, which is the best of both worlds.
